name: FreeRDP WpfRDP Build

on: [workflow_dispatch]

jobs:
  FreeRDP-build-actions:
    runs-on: win-runner-vm
    steps:
      - run: echo "The job was automatically triggered by a ${{ gitea.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The repository has been cloned to the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ gitea.workspace }}
      - name: Test msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64 
      - run: msbuild /version
      - name: Prepare environment for NMAKE/MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Start Build
        run: pwsh ./setup.ps1
        working-directory: ${{ gitea.workspace }}/winscripts
      - name: Release
        uses: akkuman/gitea-release-action@v1
        env:
          NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
        with:
          name: "FreeRDP v${{ github.run_number }}"
          tag_name: "v${{ github.run_number }}"
          body: "Automated build release v${{ github.run_number }} with wfreerdp embedded enhancements."
          files: |-
            freerdpinstall/bin/*.*
            freerdpinstall/build-wfreerdp-win32.zip
      - run: echo "This job's status is ${{ job.status }}."
