rmdir /S /Q cJSON
rmdir /S /Q cJSON-build
rmdir /S /Q libusb-cmake
rmdir /S /Q libusb-cmake-build
rmdir /S /Q openssl
rmdir /S /Q SDL
rmdir /S /Q SDL_image
rmdir /S /Q SDL_image-build
rmdir /S /Q SDL_ttf
rmdir /S /Q SDL_ttf-build
rmdir /S /Q SDL-build
rmdir /S /Q uriparser
rmdir /S /Q uriparser-build
rmdir /S /Q zlib
rmdir /S /Q zlib-build